import type { Asset } from "../assets";
import type { Dossier } from "../dossiers";

// Second batch of Edition 01 sample listings. Illustrative only: no real
// seller stands behind these records.

type Entry = { asset: Asset; dossier: Dossier };

const entries: Entry[] = [
  {
    asset: {
      id: "MX-070", slug: "quorum", name: "Quorum", type: "Meeting scheduling SaaS", category: "product", deal: "sell", status: "live",
      price: 210000, ageMonths: 27, listed: "2026-09-27",
      summary: "Round-robin scheduling for sales teams, with calendar sync.",
      description: "A scheduling product for B2B sales teams: round-robin routing, Google and Outlook calendar sync, and booking pages with qualification questions.",
      review: "Evidence reviewed", access: "Private demo after accepted enquiry",
      route: "Repository, deployment and 30-day handover", transferWindow: "30 days",
      includes: ["Application source", "Booking page builder", "Calendar sync service", "Founder handover"],
      works: ["Google and Outlook two-way sync", "Round-robin and weighted routing", "Booking pages with custom questions"],
      depends: ["Google and Microsoft OAuth apps must be re-registered by the buyer"],
      excluded: ["Existing customer workspaces", "Company name and domain"],
      metric: { value: "2,940", label: "meetings booked last month" },
      bars: [38, 44, 51, 49, 58, 63, 61, 70, 76, 74, 83, 88], sample: "analytics",
      specimen: { image: "object", position: "40% center" },
    },
    dossier: {
      highlights: ["2,940 meetings booked last month", "Google and Outlook sync", "Round-robin routing"],
      series: { label: "Meetings booked per month", values: [1210, 1380, 1520, 1490, 1760, 1900, 1870, 2150, 2380, 2310, 2620, 2940] },
      financials: { revenue: "₹52,000 to ₹58,000 / month", costs: "₹11,000 / month", note: "Revenue from 38 paying teams; contracts stay with the seller." },
      stack: ["Next.js", "Node.js", "Postgres", "Redis", "Google Calendar API"],
      seller: { role: "Two co-founders", city: "Chennai", team: "2 people" },
      reason: "The founders are moving into a larger sales-tech company and want Quorum maintained.",
      idealBuyer: "A CRM or sales-tooling company adding native scheduling.",
      evidence: [["Repository history", "Verified"], ["Calendar sync runbook", "Verified"], ["Revenue export", "Provided"], ["OAuth app ownership", "On request"]],
      faq: [["Do the booking links keep working?", "Only after the buyer connects their own OAuth apps; the handover covers the steps."]],
    },
  },
  {
    asset: {
      id: "MX-073", slug: "parcelboard", name: "Parcelboard", type: "Logistics tracking dashboard", category: "product", deal: "sell", status: "live",
      price: 165000, ageMonths: 19, listed: "2026-08-22",
      summary: "Shipment tracking across eight Indian carriers in one view.",
      description: "A tracking dashboard for D2C brands that pulls shipment status from eight Indian carriers, flags delays and sends branded delivery updates.",
      review: "Evidence reviewed", access: "Guided product walkthrough",
      route: "Repository transfer and carrier-integration notes", transferWindow: "21 days",
      includes: ["Application source", "Eight carrier connectors", "Notification templates", "Operator notes"],
      works: ["Delay detection and alerts", "Branded tracking pages", "WhatsApp and email updates"],
      depends: ["Carrier API keys are issued to the buyer's own company"],
      excluded: ["Shipment history of current customers"],
      metric: { value: "8", label: "carrier integrations" },
      bars: [30, 36, 42, 47, 52, 55, 61, 64, 70, 72, 78, 81], sample: "analytics",
      specimen: { image: "detail", position: "30% center" },
    },
    dossier: {
      highlights: ["Eight carrier integrations", "Delay alerts", "Branded tracking pages"],
      series: { label: "Shipments tracked per month, thousands", values: [14, 17, 21, 23, 26, 28, 31, 33, 36, 38, 41, 44] },
      financials: { revenue: "₹31,000 / month", costs: "₹8,500 / month", note: "From 22 D2C brands on monthly plans." },
      stack: ["React", "Go", "Postgres", "Carrier APIs"],
      seller: { role: "Solo founder", city: "Ahmedabad", team: "1 person, 1 contractor" },
      reason: "The founder is joining a logistics company full time.",
      idealBuyer: "A shipping aggregator or e-commerce tooling company.",
      evidence: [["Repository history", "Verified"], ["Carrier contracts summary", "Provided"], ["Revenue export", "Provided"]],
      faq: [["Are carrier contracts transferred?", "No. The buyer applies for carrier API access in their own company name; connectors are ready."]],
    },
  },
  {
    asset: {
      id: "MX-076", slug: "tally-desk", name: "Tally Desk", type: "Bookkeeping for freelancers", category: "product", deal: "rent", status: "live",
      price: 14000, priceUnit: "month", ageMonths: 15, listed: "2026-07-30",
      summary: "Invoices, expenses and GST summaries for independent professionals.",
      description: "A bookkeeping product for freelancers: invoices, expense capture, GST summaries and a quarterly tax estimate. Offered as a white-label licence.",
      review: "Evidence ready", access: "Sandbox account after accepted enquiry",
      route: "White-label source licence, monthly", transferWindow: "7 days",
      includes: ["White-label source", "Deployment guide", "Tax-rule tables"],
      works: ["GST invoice numbering", "Receipt capture by photo", "Quarterly advance-tax estimate"],
      depends: ["Tax tables must be kept current by the licensee"],
      excluded: ["Ownership of the codebase", "Existing user accounts"],
      metric: { value: "640", label: "active freelancers" },
      bars: [22, 28, 33, 39, 44, 48, 53, 57, 61, 66, 69, 74], sample: "analytics",
      specimen: { image: "object", position: "70% center" },
    },
    dossier: {
      highlights: ["White-label licence", "GST-ready invoicing", "Quarterly tax estimate"],
      series: { label: "Active freelancers", values: [180, 230, 270, 320, 360, 400, 440, 470, 510, 560, 600, 640] },
      stack: ["SvelteKit", "Postgres", "OCR service"],
      seller: { role: "Accounting-software team", city: "Bengaluru", team: "Team of 4" },
      reason: "The team licenses the product so others can run it under their own brand.",
      idealBuyer: "A fintech or co-working brand that wants its own bookkeeping product.",
      evidence: [["Source licence terms", "Verified"], ["Tax-rule change log", "Provided"]],
      faq: [["Can we change the branding?", "Yes. The licence is white-label: name, colours and domain are yours."]],
    },
  },
  {
    asset: {
      id: "MX-079", slug: "signalkit", name: "Signalkit", type: "Feature-flag SDK", category: "code", deal: "sell", status: "live",
      price: 88000, ageMonths: 21, listed: "2026-09-10",
      summary: "A self-hosted feature-flag service with four SDKs.",
      description: "A self-hosted feature-flag service with percentage rollouts, targeting rules and SDKs for TypeScript, Python, Go and Kotlin.",
      review: "Evidence reviewed", access: "Read-only repository review",
      route: "Repository and package ownership transfer", transferWindow: "10 days",
      includes: ["Flag service source", "Four SDKs", "Admin console", "Test suite"],
      works: ["Percentage rollouts", "Targeting by user attributes", "Audit log of flag changes"],
      depends: ["Package registry ownership moves separately per SDK"],
      excluded: ["Hosted instances of current users"],
      metric: { value: "4", label: "language SDKs" },
      bars: [35, 38, 44, 50, 53, 59, 62, 68, 71, 75, 80, 84], sample: "code",
      specimen: { image: "detail", position: "55% center" },
    },
    dossier: {
      highlights: ["Four language SDKs", "Percentage rollouts", "Full audit log"],
      series: { label: "SDK downloads per month, thousands", values: [3.1, 3.6, 4.2, 4.8, 5.1, 5.9, 6.3, 7.0, 7.4, 8.1, 8.8, 9.6] },
      stack: ["Go", "TypeScript", "Python", "Kotlin", "Postgres"],
      seller: { role: "Platform engineer", city: "Pune", team: "1 person" },
      reason: "Built as an open-core project; the author wants a company to own and fund it.",
      idealBuyer: "A developer-tools company or a platform team that wants in-house flags.",
      evidence: [["Repository history", "Verified"], ["Package ownership", "Provided"], ["Test coverage report", "Verified"]],
      faq: [["Is it open source today?", "The core is source-available; the licence moves with the transfer."]],
    },
  },
  {
    asset: {
      id: "MX-082", slug: "inkwell", name: "Inkwell", type: "Headless Markdown CMS", category: "code", deal: "sell", status: "live",
      price: 72000, ageMonths: 17, listed: "2026-08-14",
      summary: "A Git-backed CMS with a clean editor for non-developers.",
      description: "A headless CMS that stores Markdown in Git, gives writers a clean editor and publishes through webhooks to any static site.",
      review: "Route documented", access: "Live editor demo",
      route: "Repository transfer", transferWindow: "7 days",
      includes: ["Editor and API source", "GitHub and GitLab adapters", "Webhook publisher"],
      works: ["Rich Markdown editor", "Image handling to Git LFS", "Scheduled publishing"],
      depends: ["GitHub app registration is recreated by the buyer"],
      excluded: ["Hosted customer workspaces"],
      metric: { value: "310", label: "GitHub stars" },
      bars: [40, 42, 47, 50, 55, 58, 60, 66, 69, 71, 76, 79], sample: "code",
      specimen: { image: "object", position: "25% center" },
    },
    dossier: {
      highlights: ["Git-backed content", "Writer-friendly editor", "Scheduled publishing"],
      series: { label: "Workspaces created per month", values: [18, 22, 25, 29, 31, 36, 39, 44, 47, 52, 55, 61] },
      stack: ["TypeScript", "React", "Node.js", "GitHub API"],
      seller: { role: "Indie developer", city: "Kolkata", team: "1 person" },
      reason: "The developer has moved to a full-time role and cannot maintain it.",
      idealBuyer: "A static-site or hosting company adding content editing.",
      evidence: [["Repository history", "Verified"], ["GitHub app settings", "Provided"]],
      faq: [["Does it work with any static site generator?", "Yes, it publishes Markdown and triggers a webhook; the generator is your choice."]],
    },
  },
  {
    asset: {
      id: "MX-085", slug: "brightline", name: "Brightline", type: "Domain and identity", category: "domain", deal: "sell", status: "live",
      price: 96000, ageMonths: 62, listed: "2026-09-19",
      summary: "A two-word .co name with a finished fintech identity.",
      description: "A clean two-word .co domain with a complete fintech identity: wordmark, symbol, colour system and a sixteen-page brand book.",
      review: "Route documented", access: "Registrar proof after accepted enquiry",
      route: "Registrar transfer and brand files", transferWindow: "5–7 days",
      includes: [".co domain", "Brand book", "Symbol and wordmark masters", "Colour and type system"],
      works: ["Domain renewed for two more years", "Editable brand masters"],
      depends: ["Registrar transfer lock is lifted before completion"],
      excluded: ["Trademark registration"],
      metric: { value: "16", label: "brand-book pages" },
      bars: [55, 55, 60, 60, 62, 62, 66, 66, 70, 70, 74, 74], sample: "domain",
      specimen: { image: "detail", position: "85% center" },
    },
    dossier: {
      highlights: ["Short two-word .co", "Full fintech identity", "Renewed for two years"],
      series: { label: "Monthly type-in visits", values: [90, 96, 101, 99, 110, 118, 115, 124, 130, 128, 136, 141] },
      stack: ["Registrar transfer", "Figma masters", "Brand book PDF"],
      seller: { role: "Brand studio", city: "Delhi", team: "Studio of 6" },
      reason: "Created for a fintech client that changed direction before launch.",
      idealBuyer: "A payments or lending start-up choosing its name.",
      evidence: [["Registrar ownership record", "Verified"], ["Brand book", "Provided"]],
      faq: [["Is the identity exclusive?", "Yes. All masters and rights move with the domain."]],
    },
  },
  {
    asset: {
      id: "MX-088", slug: "tamarind", name: "Tamarind", type: "Domain and identity", category: "domain", deal: "sell", status: "live",
      price: 46000, ageMonths: 41, listed: "2026-07-18",
      summary: "A warm .in food-brand name with packaging-ready identity.",
      description: "A memorable .in name with an identity designed for a packaged-food brand: wordmark, label system and a pattern library.",
      review: "Route documented", access: "Registrar proof after accepted enquiry",
      route: "Registrar transfer and identity files", transferWindow: "5–7 days",
      includes: [".in domain", "Wordmark masters", "Label system", "Pattern library"],
      works: ["Print-ready label templates", "Clean registrar history"],
      depends: ["Registrar eligibility for .in is confirmed before transfer"],
      excluded: ["Recipes or product formulations"],
      metric: { value: "3 yrs", label: "continuous ownership" },
      bars: [40, 40, 44, 44, 48, 48, 52, 52, 55, 55, 59, 59], sample: "domain",
      specimen: { image: "object", position: "15% center" },
    },
    dossier: {
      highlights: ["Short .in name", "Packaging-ready labels", "Pattern library included"],
      series: { label: "Monthly type-in visits", values: [60, 62, 65, 63, 70, 72, 74, 77, 80, 83, 85, 90] },
      stack: ["Registrar transfer", "Illustrator masters"],
      seller: { role: "Independent designer", city: "Mysuru", team: "1 person" },
      reason: "Designed for a food brand that never launched.",
      idealBuyer: "A food or beverage start-up at the naming stage.",
      evidence: [["Registrar ownership record", "Verified"], ["Label files", "Provided"]],
      faq: [["Are the labels print-ready?", "Yes. Dielines and CMYK masters are included."]],
    },
  },
  {
    asset: {
      id: "MX-091", slug: "mono-grid", name: "Mono Grid", type: "Editorial layout system", category: "design", deal: "rent", status: "live",
      price: 26000, priceUnit: "year", ageMonths: 13, listed: "2026-09-05",
      summary: "A twelve-column editorial system for long-form publishing.",
      description: "An editorial layout system for publishers: a twelve-column grid, type scale, 40 article modules and dark-mode tokens, licensed per publication.",
      review: "Evidence ready", access: "Read-only library review",
      route: "Non-exclusive yearly licence", transferWindow: "3 days",
      includes: ["40 article modules", "Type scale", "Grid and spacing tokens", "Figma library"],
      works: ["Responsive article templates", "Dark-mode token set"],
      depends: ["Licensed fonts are purchased separately"],
      excluded: ["Exclusive rights"],
      metric: { value: "40", label: "article modules" },
      bars: [30, 34, 38, 42, 47, 51, 55, 60, 64, 68, 72, 77], sample: "system",
      specimen: { image: "detail", position: "45% center" },
    },
    dossier: {
      highlights: ["40 article modules", "Twelve-column grid", "Dark-mode tokens"],
      series: { label: "Active publication licences", values: [2, 3, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11] },
      stack: ["Figma", "CSS", "Design tokens"],
      seller: { role: "Editorial designer", city: "Mumbai", team: "1 person" },
      reason: "Offered as a licence after being used across three publications.",
      idealBuyer: "A digital magazine or newsroom redesigning its article pages.",
      evidence: [["Figma library", "Verified"], ["Font licence notes", "Provided"]],
      faq: [["Can we use it for more than one publication?", "Each licence covers one publication for one year."]],
    },
  },
  {
    asset: {
      id: "MX-093", slug: "fieldnotes", name: "Fieldnotes", type: "Form component kit", category: "design", deal: "sell", status: "live",
      price: 38000, ageMonths: 10, listed: "2026-09-24",
      summary: "Accessible form components with validation patterns.",
      description: "A kit of 52 accessible form components with validation, error and empty states, built in Figma and React.",
      review: "Evidence ready", access: "Read-only library review",
      route: "Full assignment of design and code", transferWindow: "7 days",
      includes: ["52 components", "Validation patterns", "React package", "Figma library"],
      works: ["Keyboard and screen-reader tested", "Error and empty states"],
      depends: ["None recorded"],
      excluded: ["Future updates after transfer"],
      metric: { value: "52", label: "form components" },
      bars: [20, 26, 31, 37, 42, 46, 50, 55, 59, 64, 68, 72], sample: "system",
      specimen: { image: "object", position: "60% center" },
    },
    dossier: {
      highlights: ["52 accessible components", "Validation patterns", "Figma and React"],
      series: { label: "Components shipped, cumulative", values: [8, 13, 18, 22, 27, 31, 35, 39, 43, 47, 50, 52] },
      stack: ["Figma", "React", "TypeScript", "Storybook"],
      seller: { role: "Accessibility consultant", city: "Bengaluru", team: "1 person" },
      reason: "Built for client work; the consultant is focusing on audits.",
      idealBuyer: "A product team or agency that needs accessible forms fast.",
      evidence: [["Accessibility test notes", "Verified"], ["React package source", "Verified"]],
      faq: [["Which screen readers were tested?", "NVDA, VoiceOver and TalkBack; notes are in the handover."]],
    },
  },
  {
    asset: {
      id: "MX-095", slug: "ledger-docs", name: "Ledger Docs", type: "Documentation site template", category: "template", deal: "rent", status: "live",
      price: 12000, priceUnit: "year", ageMonths: 8, listed: "2026-09-16",
      summary: "A documentation template with search and versioning.",
      description: "A documentation site template with full-text search, version switching, API reference pages and a changelog, licensed per product.",
      review: "Evidence ready", access: "Live preview",
      route: "Non-exclusive yearly licence", transferWindow: "2 days",
      includes: ["Docs template", "API reference layout", "Search setup guide"],
      works: ["Version switcher", "Full-text search", "Dark mode"],
      depends: ["Search index is hosted by the licensee"],
      excluded: ["Content writing"],
      metric: { value: "14", label: "page layouts" },
      bars: [25, 29, 33, 38, 41, 45, 50, 54, 57, 61, 65, 70], sample: "template",
      specimen: { image: "detail", position: "10% center" },
    },
    dossier: {
      highlights: ["Version switcher", "Built-in search", "API reference pages"],
      series: { label: "Active licences", values: [1, 2, 4, 5, 7, 9, 10, 12, 14, 15, 17, 19] },
      stack: ["Astro", "MDX", "Pagefind"],
      seller: { role: "Developer advocate", city: "Hyderabad", team: "1 person" },
      reason: "Licensed so other developer products can launch docs quickly.",
      idealBuyer: "An API or SDK company launching its documentation.",
      evidence: [["Live preview", "Verified"], ["Licence terms", "Provided"]],
      faq: [["Can we self-host search?", "Yes, search runs as a static index with no external service."]],
    },
  },
  {
    asset: {
      id: "MX-097", slug: "shopfront", name: "Shopfront", type: "D2C store template", category: "template", deal: "sell", status: "live",
      price: 34000, ageMonths: 12, listed: "2026-08-28",
      summary: "A fast storefront template for single-brand D2C shops.",
      description: "A storefront template for single-brand D2C shops: product, collection, cart and editorial pages, tuned for fast mobile loads.",
      review: "Evidence ready", access: "Live preview",
      route: "Full assignment of the template", transferWindow: "5 days",
      includes: ["11 page templates", "Section library", "Performance notes"],
      works: ["Mobile-first product pages", "Editorial lookbook sections"],
      depends: ["Commerce backend is provided by the buyer"],
      excluded: ["Product photography"],
      metric: { value: "11", label: "page templates" },
      bars: [44, 44, 44, 58, 58, 58, 66, 66, 66, 74, 74, 74], sample: "template",
      specimen: { image: "object", position: "35% center" },
    },
    dossier: {
      highlights: ["11 page templates", "Mobile-first product pages", "Lookbook sections"],
      series: { label: "Stores launched with it", values: [0, 1, 1, 2, 3, 3, 4, 5, 6, 6, 7, 8] },
      stack: ["Next.js", "Tailwind", "Headless commerce"],
      seller: { role: "E-commerce designer", city: "Jaipur", team: "Studio of 2" },
      reason: "The studio is moving to custom builds only.",
      idealBuyer: "A D2C brand or agency launching single-brand stores.",
      evidence: [["Live preview", "Verified"], ["Performance report", "Provided"]],
      faq: [["Which commerce backends work?", "Any headless backend; adapters for two common ones are included."]],
    },
  },
  {
    asset: {
      id: "MX-099", slug: "pantry-pal", name: "Pantry Pal", type: "Android grocery-list app", category: "provider", deal: "sell", status: "live",
      price: 68000, ageMonths: 23, listed: "2026-09-12",
      summary: "A Play Store grocery app moved through Google's app transfer.",
      description: "A shared grocery-list app on Google Play with household sync, moved through Google Play's own app-transfer process so ratings stay attached.",
      review: "Route documented", access: "Internal test build after accepted enquiry",
      route: "Google Play app transfer and repository", transferWindow: "7–14 days",
      includes: ["Kotlin source", "Play listing via app transfer", "Design files"],
      works: ["Household sharing", "Offline lists", "Barcode scan"],
      depends: ["Google Play app-transfer eligibility for both accounts"],
      excluded: ["User data", "The seller's developer account"],
      metric: { value: "4.4", label: "Play Store rating" },
      bars: [48, 52, 55, 53, 60, 63, 62, 67, 70, 68, 74, 77], sample: "app",
      specimen: { image: "detail", position: "70% center" },
    },
    dossier: {
      highlights: ["4.4 Play Store rating", "Household sync", "Moves by Google's app transfer"],
      series: { label: "Monthly active users", values: [5200, 5600, 5900, 5750, 6300, 6700, 6600, 7100, 7400, 7300, 7900, 8300] },
      financials: { revenue: "₹9,000 to ₹12,000 / month", costs: "₹1,500 / month", note: "Ad and pro-upgrade revenue." },
      stack: ["Kotlin", "Jetpack Compose", "Firebase"],
      seller: { role: "Indie developer", city: "Lucknow", team: "1 person" },
      reason: "The developer is focusing on a paid productivity app.",
      idealBuyer: "An app studio with an Android portfolio.",
      evidence: [["Play Console ownership", "Verified"], ["Kotlin source", "Verified"], ["Revenue export", "Provided"]],
      faq: [["What happens to Firebase?", "The buyer creates their own Firebase project; migration steps are documented."]],
    },
  },
  {
    asset: {
      id: "MX-101", slug: "studio-calm", name: "Studio Calm", type: "Chrome focus extension", category: "provider", deal: "sell", status: "live",
      price: 42000, ageMonths: 31, listed: "2026-08-03",
      summary: "A focus-timer extension with 18,000 weekly users.",
      description: "A Chrome extension that blocks distracting sites during focus sessions, with a calm timer, streaks and a weekly report.",
      review: "Route documented", access: "Unlisted test version after accepted enquiry",
      route: "Chrome Web Store ownership transfer and repository", transferWindow: "7 days",
      includes: ["Extension source", "Store listing transfer", "Brand assets"],
      works: ["Site blocking during sessions", "Streaks and weekly report"],
      depends: ["Chrome Web Store publisher transfer rules apply"],
      excluded: ["User data"],
      metric: { value: "18k", label: "weekly users" },
      bars: [60, 62, 64, 63, 67, 69, 71, 70, 74, 76, 78, 80], sample: "app",
      specimen: { image: "object", position: "90% center" },
    },
    dossier: {
      highlights: ["18,000 weekly users", "Calm focus timer", "Store listing moves with it"],
      series: { label: "Weekly users, thousands", values: [12.1, 12.8, 13.4, 13.2, 14.3, 15.0, 15.4, 15.1, 16.2, 16.9, 17.4, 18.0] },
      stack: ["TypeScript", "Chrome Extensions MV3"],
      seller: { role: "Product designer", city: "Kochi", team: "1 person" },
      reason: "The designer has less time for maintenance after a new job.",
      idealBuyer: "A productivity company or an indie maker with an extension portfolio.",
      evidence: [["Web Store publisher record", "Verified"], ["Extension source", "Verified"]],
      faq: [["Does it collect browsing data?", "No. Block lists stay on the device; nothing personal transfers."]],
    },
  },
  {
    asset: {
      id: "MX-103", slug: "tabletop", name: "Tabletop", type: "Shopify restaurant app", category: "provider", deal: "rent", status: "rented",
      price: 11000, priceUnit: "month", ageMonths: 18, listed: "2026-07-09",
      summary: "Table reservations inside Shopify, currently licensed.",
      description: "A Shopify app that adds table reservations and pre-orders to restaurant storefronts. It is currently licensed and shown for reference.",
      review: "Licence active", access: "Closed record",
      route: "Monthly source licence", transferWindow: "3 days",
      includes: ["App source", "Setup guide"],
      works: ["Reservation calendar", "Pre-orders with deposits"],
      depends: ["The licensee runs the app under their own Shopify Partner account"],
      excluded: ["App Store listing", "Merchant data"],
      metric: { value: "46", label: "installing restaurants" },
      bars: [40, 44, 47, 50, 53, 55, 58, 61, 63, 66, 69, 71], sample: "app",
      specimen: { image: "detail", position: "20% center" },
    },
    dossier: {
      highlights: ["Reservations inside Shopify", "Pre-orders with deposits", "Currently licensed"],
      series: { label: "Installing restaurants", values: [12, 15, 18, 20, 24, 27, 30, 33, 37, 40, 43, 46] },
      stack: ["Remix", "Shopify App Bridge", "Postgres"],
      seller: { role: "Restaurant-tech team", city: "Goa", team: "Team of 3" },
      reason: "Licensed monthly to teams building for restaurants.",
      idealBuyer: "Currently rented. Shown as a reference for an active licence.",
      evidence: [["Licence agreement template", "Verified"]],
      faq: [["When will it be available again?", "When the current licence ends. Ask to be told."]],
    },
  },
];

export const moreAssets = entries.map((entry) => entry.asset);
export const moreDossiers: Record<string, Dossier> = Object.fromEntries(entries.map((entry) => [entry.asset.slug, entry.dossier]));
